name: Gridded SPC Outlooks

on:
  push
  #schedule:
  #  - cron: '10 1,4,7,12,13,17,20 * * *'
  #  - cron: '40 8,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    #- uses: actions/cache@v1
    #  with:
    #    path: ~/.cash/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: ${{ runner.os }}-pip-

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        miniconda-version: latest
        activate-environment: foo
        python-version: 3.7
    - name: Bash
      shell: bash -l {0}
      run: |
        conda info
        conda list
        
    #- uses: actions/checkout@v2
    #- name: Set up Python 3.7.7
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.7
      
    - name: Install dependencies
      run: |
        sudo apt-get install libproj-dev
        conda install -c conda-forge wheel numpy geos pandas geopandas requests pyshp matplotlib cartopy

    - name: List files 
      run: |
        pwd
        ls -la
        cd ../
        pwd
        ls -la
        cd ../
        pwd
        ls -la
        cd ../
        pwd
        ls -la
        cd ../
        pwd
        ls -la

    - name: Run code
      run: python grid_SPC_outlook.py

    - name: Commit files
      run: |
          git config --local user.email ${{ secrets.SECRET_MAIL_FROM }}
          git config --local user.name ${{ secrets.SECRET_GITHUB_USERNAME }}
          git add .        # Adds file to commit
          git add --all    # Adds only the file, not the Python setup folder.
          # git commit -m "Add changes"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
