name: Gridded SPC Outlooks

on:
  push
  #schedule:
  #  - cron: '10 1,4,7,12,13,17,20 * * *'
  #  - cron: '40 8,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    #- name: Update pip
      #run: |
        #curl https://bootstrap.pypa.io/get-pip.py | python
        #pip install --upgrade setuptools
      
    - name: Install dependencies
      run: |
        sudo apt-get install libproj-dev
        pip3 install wheel numpy geos pandas geopandas requests pyshp matplotlib cartopy
    #- name: Install libproj-dev
    #  run: sudo apt-get install libproj-dev
    #- name: Install shapely
    #  run: |
    #    pip3 uninstall shapely
    #    pip3 install shapely --no-binary shapely
    #- name: Install numpy
    #  run: pip install numpy
    #- name: Install pandas geopandas
    #  run: pip install pandas geopandas
    #- name: Install requests
    #  run: pip install requests
    #- name: Install geos
    #  run: pip install geos
    #- name: Install pyshp
    #  run: pip install pyshp
    #- name: Install matplotlib
    #  run: pip install matplotlib
    - name: List installed packages
      run: pip3 list
    #- name: Install cartopy 
    #  run: pip3 install cartopy

    - name: Run code
      run: python grid_SPC_outlook.py

    - name: Commit files
      run: |
          git config --local user.email ${{ secrets.SECRET_MAIL_FROM }}
          git config --local user.name ${{ secrets.SECRET_GITHUB_USERNAME }}
          git add .        # Adds file to commit
          git add --all    # Adds only the file, not the Python setup folder.
          # git commit -m "Add changes"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
