name: Gridded SPC Outlooks

on:
  push
  #schedule:
  #  - cron: '10 1,4,7,12,13,17,20 * * *'
  #  - cron: '40 8,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    #- uses: actions/cache@v1
    #  with:
    #    path: ~/.cash/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: ${{ runner.os }}-pip-

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        miniconda-version: latest
        activate-environment: test
        python-version: 3.7
    - name: Show conda list
      run: |
        conda env list
        conda env list | grep -v "^$\|#" |awk '{print $1;}'|xargs -I{} -d "\n" sh -c 'printf "Env: {}\t"; conda list -n {} |grep "^python\s";'
        conda init bash
        conda activate test
        conda env list
      #shell: bash
      
    - name: Install dependencies
      run: |
        sudo apt-get install libproj-dev
        conda install -c conda-forge wheel numpy geos pandas geopandas requests pyshp matplotlib cartopy
        python -V

    - name: Run code
      shell: bash
      run: |
        #conda activate foo
        python -V
        python grid_SPC_outlook.py

    - name: Commit files
      run: |
          git config --local user.email ${{ secrets.SECRET_MAIL_FROM }}
          git config --local user.name ${{ secrets.SECRET_GITHUB_USERNAME }}
          git add .        # Adds file to commit
          git add --all    # Adds only the file, not the Python setup folder.
          # git commit -m "Add changes"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
